# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/asheshvidyut/rsquare

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/asheshvidyut/rsquare

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/asheshvidyut/rsquare/CMakeFiles /Users/asheshvidyut/rsquare//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/asheshvidyut/rsquare/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test_radix

# Build rule for target.
test_radix: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_radix
.PHONY : test_radix

# fast build rule for target.
test_radix/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_radix.dir/build.make CMakeFiles/test_radix.dir/build
.PHONY : test_radix/fast

#=============================================================================
# Target rules for targets named rsquare

# Build rule for target.
rsquare: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 rsquare
.PHONY : rsquare

# fast build rule for target.
rsquare/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rsquare.dir/build.make CMakeFiles/rsquare.dir/build
.PHONY : rsquare/fast

radix/iterator.o: radix/iterator.cpp.o
.PHONY : radix/iterator.o

# target to build an object file
radix/iterator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_radix.dir/build.make CMakeFiles/test_radix.dir/radix/iterator.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rsquare.dir/build.make CMakeFiles/rsquare.dir/radix/iterator.cpp.o
.PHONY : radix/iterator.cpp.o

radix/iterator.i: radix/iterator.cpp.i
.PHONY : radix/iterator.i

# target to preprocess a source file
radix/iterator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_radix.dir/build.make CMakeFiles/test_radix.dir/radix/iterator.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rsquare.dir/build.make CMakeFiles/rsquare.dir/radix/iterator.cpp.i
.PHONY : radix/iterator.cpp.i

radix/iterator.s: radix/iterator.cpp.s
.PHONY : radix/iterator.s

# target to generate assembly for a file
radix/iterator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_radix.dir/build.make CMakeFiles/test_radix.dir/radix/iterator.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rsquare.dir/build.make CMakeFiles/rsquare.dir/radix/iterator.cpp.s
.PHONY : radix/iterator.cpp.s

radix/main.o: radix/main.cpp.o
.PHONY : radix/main.o

# target to build an object file
radix/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_radix.dir/build.make CMakeFiles/test_radix.dir/radix/main.cpp.o
.PHONY : radix/main.cpp.o

radix/main.i: radix/main.cpp.i
.PHONY : radix/main.i

# target to preprocess a source file
radix/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_radix.dir/build.make CMakeFiles/test_radix.dir/radix/main.cpp.i
.PHONY : radix/main.cpp.i

radix/main.s: radix/main.cpp.s
.PHONY : radix/main.s

# target to generate assembly for a file
radix/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_radix.dir/build.make CMakeFiles/test_radix.dir/radix/main.cpp.s
.PHONY : radix/main.cpp.s

radix/node.o: radix/node.cpp.o
.PHONY : radix/node.o

# target to build an object file
radix/node.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_radix.dir/build.make CMakeFiles/test_radix.dir/radix/node.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rsquare.dir/build.make CMakeFiles/rsquare.dir/radix/node.cpp.o
.PHONY : radix/node.cpp.o

radix/node.i: radix/node.cpp.i
.PHONY : radix/node.i

# target to preprocess a source file
radix/node.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_radix.dir/build.make CMakeFiles/test_radix.dir/radix/node.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rsquare.dir/build.make CMakeFiles/rsquare.dir/radix/node.cpp.i
.PHONY : radix/node.cpp.i

radix/node.s: radix/node.cpp.s
.PHONY : radix/node.s

# target to generate assembly for a file
radix/node.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_radix.dir/build.make CMakeFiles/test_radix.dir/radix/node.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rsquare.dir/build.make CMakeFiles/rsquare.dir/radix/node.cpp.s
.PHONY : radix/node.cpp.s

radix/radix.o: radix/radix.cpp.o
.PHONY : radix/radix.o

# target to build an object file
radix/radix.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_radix.dir/build.make CMakeFiles/test_radix.dir/radix/radix.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rsquare.dir/build.make CMakeFiles/rsquare.dir/radix/radix.cpp.o
.PHONY : radix/radix.cpp.o

radix/radix.i: radix/radix.cpp.i
.PHONY : radix/radix.i

# target to preprocess a source file
radix/radix.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_radix.dir/build.make CMakeFiles/test_radix.dir/radix/radix.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rsquare.dir/build.make CMakeFiles/rsquare.dir/radix/radix.cpp.i
.PHONY : radix/radix.cpp.i

radix/radix.s: radix/radix.cpp.s
.PHONY : radix/radix.s

# target to generate assembly for a file
radix/radix.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_radix.dir/build.make CMakeFiles/test_radix.dir/radix/radix.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rsquare.dir/build.make CMakeFiles/rsquare.dir/radix/radix.cpp.s
.PHONY : radix/radix.cpp.s

radix/rev_iterator.o: radix/rev_iterator.cpp.o
.PHONY : radix/rev_iterator.o

# target to build an object file
radix/rev_iterator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_radix.dir/build.make CMakeFiles/test_radix.dir/radix/rev_iterator.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rsquare.dir/build.make CMakeFiles/rsquare.dir/radix/rev_iterator.cpp.o
.PHONY : radix/rev_iterator.cpp.o

radix/rev_iterator.i: radix/rev_iterator.cpp.i
.PHONY : radix/rev_iterator.i

# target to preprocess a source file
radix/rev_iterator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_radix.dir/build.make CMakeFiles/test_radix.dir/radix/rev_iterator.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rsquare.dir/build.make CMakeFiles/rsquare.dir/radix/rev_iterator.cpp.i
.PHONY : radix/rev_iterator.cpp.i

radix/rev_iterator.s: radix/rev_iterator.cpp.s
.PHONY : radix/rev_iterator.s

# target to generate assembly for a file
radix/rev_iterator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_radix.dir/build.make CMakeFiles/test_radix.dir/radix/rev_iterator.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rsquare.dir/build.make CMakeFiles/rsquare.dir/radix/rev_iterator.cpp.s
.PHONY : radix/rev_iterator.cpp.s

rsquare.o: rsquare.cpp.o
.PHONY : rsquare.o

# target to build an object file
rsquare.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rsquare.dir/build.make CMakeFiles/rsquare.dir/rsquare.cpp.o
.PHONY : rsquare.cpp.o

rsquare.i: rsquare.cpp.i
.PHONY : rsquare.i

# target to preprocess a source file
rsquare.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rsquare.dir/build.make CMakeFiles/rsquare.dir/rsquare.cpp.i
.PHONY : rsquare.cpp.i

rsquare.s: rsquare.cpp.s
.PHONY : rsquare.s

# target to generate assembly for a file
rsquare.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rsquare.dir/build.make CMakeFiles/rsquare.dir/rsquare.cpp.s
.PHONY : rsquare.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... rsquare"
	@echo "... test_radix"
	@echo "... radix/iterator.o"
	@echo "... radix/iterator.i"
	@echo "... radix/iterator.s"
	@echo "... radix/main.o"
	@echo "... radix/main.i"
	@echo "... radix/main.s"
	@echo "... radix/node.o"
	@echo "... radix/node.i"
	@echo "... radix/node.s"
	@echo "... radix/radix.o"
	@echo "... radix/radix.i"
	@echo "... radix/radix.s"
	@echo "... radix/rev_iterator.o"
	@echo "... radix/rev_iterator.i"
	@echo "... radix/rev_iterator.s"
	@echo "... rsquare.o"
	@echo "... rsquare.i"
	@echo "... rsquare.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

