# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/asheshvidyut/cpp-immutable-radix

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/asheshvidyut/cpp-immutable-radix

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/asheshvidyut/cpp-immutable-radix/CMakeFiles /Users/asheshvidyut/cpp-immutable-radix//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/asheshvidyut/cpp-immutable-radix/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named iradix-cpp

# Build rule for target.
iradix-cpp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 iradix-cpp
.PHONY : iradix-cpp

# fast build rule for target.
iradix-cpp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iradix-cpp.dir/build.make CMakeFiles/iradix-cpp.dir/build
.PHONY : iradix-cpp/fast

iradix/iterator.o: iradix/iterator.cpp.o
.PHONY : iradix/iterator.o

# target to build an object file
iradix/iterator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iradix-cpp.dir/build.make CMakeFiles/iradix-cpp.dir/iradix/iterator.cpp.o
.PHONY : iradix/iterator.cpp.o

iradix/iterator.i: iradix/iterator.cpp.i
.PHONY : iradix/iterator.i

# target to preprocess a source file
iradix/iterator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iradix-cpp.dir/build.make CMakeFiles/iradix-cpp.dir/iradix/iterator.cpp.i
.PHONY : iradix/iterator.cpp.i

iradix/iterator.s: iradix/iterator.cpp.s
.PHONY : iradix/iterator.s

# target to generate assembly for a file
iradix/iterator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iradix-cpp.dir/build.make CMakeFiles/iradix-cpp.dir/iradix/iterator.cpp.s
.PHONY : iradix/iterator.cpp.s

iradix/node.o: iradix/node.cpp.o
.PHONY : iradix/node.o

# target to build an object file
iradix/node.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iradix-cpp.dir/build.make CMakeFiles/iradix-cpp.dir/iradix/node.cpp.o
.PHONY : iradix/node.cpp.o

iradix/node.i: iradix/node.cpp.i
.PHONY : iradix/node.i

# target to preprocess a source file
iradix/node.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iradix-cpp.dir/build.make CMakeFiles/iradix-cpp.dir/iradix/node.cpp.i
.PHONY : iradix/node.cpp.i

iradix/node.s: iradix/node.cpp.s
.PHONY : iradix/node.s

# target to generate assembly for a file
iradix/node.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iradix-cpp.dir/build.make CMakeFiles/iradix-cpp.dir/iradix/node.cpp.s
.PHONY : iradix/node.cpp.s

iradix/tree.o: iradix/tree.cpp.o
.PHONY : iradix/tree.o

# target to build an object file
iradix/tree.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iradix-cpp.dir/build.make CMakeFiles/iradix-cpp.dir/iradix/tree.cpp.o
.PHONY : iradix/tree.cpp.o

iradix/tree.i: iradix/tree.cpp.i
.PHONY : iradix/tree.i

# target to preprocess a source file
iradix/tree.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iradix-cpp.dir/build.make CMakeFiles/iradix-cpp.dir/iradix/tree.cpp.i
.PHONY : iradix/tree.cpp.i

iradix/tree.s: iradix/tree.cpp.s
.PHONY : iradix/tree.s

# target to generate assembly for a file
iradix/tree.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iradix-cpp.dir/build.make CMakeFiles/iradix-cpp.dir/iradix/tree.cpp.s
.PHONY : iradix/tree.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iradix-cpp.dir/build.make CMakeFiles/iradix-cpp.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iradix-cpp.dir/build.make CMakeFiles/iradix-cpp.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iradix-cpp.dir/build.make CMakeFiles/iradix-cpp.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... iradix-cpp"
	@echo "... iradix/iterator.o"
	@echo "... iradix/iterator.i"
	@echo "... iradix/iterator.s"
	@echo "... iradix/node.o"
	@echo "... iradix/node.i"
	@echo "... iradix/node.s"
	@echo "... iradix/tree.o"
	@echo "... iradix/tree.i"
	@echo "... iradix/tree.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

